### ISSUE TITLE
npm scopes?

### ISSUE THREAD

**Issue by rreusser** [scijs/contributing#25]
https://docs.npmjs.com/misc/scope

Publishing would then be:

``` bash
$ npm publish --access public
```

Followed by

``` bash
$ npm install @scijs/ndgemm
```

Is that a correct or reasonable use of scopes? Would this alleviate any prefixing/naming issues?

**Comment by mikolalysenko** [comment]
I don't see anything wrong with that use.  Overall, it's an interesting idea, though I wonder if it is worth the trouble of going through and republishing everything.

What exists now is already dumped into the global scope anyway, so I don't see much harm in continuing with the pattern for now.

**Comment by rreusser** [comment]
Yeah, the status quo works, so not sure this is worth the trouble. Closing.
